spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/evaluation
    username: postgres
    password: ahmedy123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  error:
    include-message: always
logging:
  level:
    org.springframework.security: DEBUG